# WeatherCheck design tokens (shared)
wc.label.title.size = 24
wc.label.body.large.size = 18
wc.label.body.medium.size = 14
wc.label.body.small.size = 12
wc.label.body.micro.size = 10

wc.label.title.style = bold
wc.label.body.style = plain
